name: drl_cuda
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pytorch
  - pytorch-cuda            # installs the CUDAâ€enabled build
  - numpy>=1.19.5,<2.0
  - scipy
  - xarray
  - netCDF4
  - pandas
  - matplotlib
  - jupyter
  - tqdm
  - scikit-image
  - pyyaml
  - pip
  - pip:
      - tensorboard
      - torchviz
